import React from 'react';
import { Brain } from 'lucide-react';

export const HeroImageSection: React.FC = () => {
  return (
    <section className="relative min-h-[60vh] md:min-h-[80vh] overflow-hidden bg-white">
      {/* Decorative accent elements */}
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-cyan-500 to-teal-500"></div>
      <div className="absolute bottom-0 right-0 w-32 h-32 bg-cyan-50 rounded-full -mb-16 -mr-16 opacity-50 shadow-lg"></div>
      <div className="absolute top-1/4 left-1/4 w-16 h-16 bg-teal-50 rounded-full opacity-30 shadow-md"></div>
      
      {/* Content */}
      <div className="relative z-10 h-full flex flex-col md:flex-row items-stretch justify-center gap-y-8 md:gap-x-10 px-4 md:px-12 py-12">
        
        {/* Image on the left */}
        <div className="w-full md:w-1/2 h-full">
          <div className="relative w-full h-full">
            <img
              src="/assets/whyscent/image1.jpg"
              alt="Scent visualization"
              className="w-full h-full object-cover rounded-2xl shadow-2xl transition-transform duration-700 hover:translate-y-1"
            />
          </div>
        </div>
        
        {/* Text + card */}
        <div className="w-full md:w-1/2 h-full flex flex-col">
          {/* Headline + card together */}
          <div className="flex flex-col items-center justify-start h-full">
            {/* Headline centered */}
            <h1 className="text-3xl md:text-5xl font-bold text-gray-900 leading-tight mb-8 text-center animate-fade-in">
              Scent Makes an <span className="text-cyan-600">Emotional</span> Impact
            </h1>

            {/* Content card */}
            <div className="flex-1 bg-gray-50 rounded-2xl shadow-lg p-6 md:p-8 w-full animate-slide-up border-l-4 border-cyan-500 transition-all duration-700 hover:shadow-xl">
              <div className="space-y-6">
                <div className="flex items-start gap-3 transition-transform duration-500 hover:translate-x-2">
                  <Brain className="w-8 h-8 text-cyan-600 flex-shrink-0 mt-1 transition-transform duration-500 hover:scale-110" />
                  <p className="text-gray-700 text-base">
                    <span className="font-bold text-lg">Scent is the STRONGEST</span> sense linked to memory & emotion.
                  </p>
                </div>
                
                <div className="border-t border-gray-200 pt-4">
                  <h3 className="text-4xl md:text-5xl font-bold text-cyan-600 mb-2">63%</h3>
                  <p className="text-gray-600 text-base">
                    Improvement in mood when exposed to a pleasing scent.
                  </p>
                </div>
                
                <div className="border-t border-gray-200 pt-4">
                  <h3 className="text-4xl md:text-5xl font-bold text-cyan-600 mb-2">75%</h3>
                  <p className="text-gray-600 text-base">
                    Of our emotions are generated by what we smell.
                  </p>
                </div>
                
                <div className="border-t border-gray-200 pt-4">
                  <h3 className="text-4xl md:text-5xl font-bold text-cyan-600 mb-2">100x</h3>
                  <p className="text-gray-600 text-base">
                    More likely to remember what they smell vs. what they see.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
