import React from 'react';
import { Brain, Smile, Star, TrendingUp, ShoppingCart, Clock3, Wallet, Timer } from 'lucide-react';

type Point = { icon: React.ReactNode; value: string; label: string };

/** Enhanced points display with unique styling and proportional layout */
const PointsSimple: React.FC<{ points: Point[] }> = ({ points }) => (
  <ul className={`grid grid-cols-1 ${points.length <= 3 ? 'md:grid-cols-3' : 'md:grid-cols-5'} gap-6 text-center mt-8 md:mt-12`}>
    {points.map((p, i) => (
      <li key={`${i}-${String(p.value)}`} className="space-y-3 group">
        <div className="flex justify-center">
          <div className="w-16 h-16 rounded-full bg-primary flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
            {p.icon}
          </div>
        </div>
        <div className="font-extrabold text-3xl md:text-[32px] leading-none text-[#0c4384]">
          {p.value}
        </div>
        <p className="text-slate-700 text-base md:text-lg leading-relaxed max-w-xs mx-auto">
          {p.label}
        </p>
      </li>
    ))}
  </ul>
);

const BannerBlock: React.FC<{
  type: 'video' | 'image';
  src: string;
  headline: string;
  points: Point[];
  poster?: string;
  isReversed?: boolean;
  description?: string;
}> = ({ type, src, headline, points, poster, isReversed = false, description }) => {
  return (
    <section className={`relative w-full py-12 md:py-16 ${isReversed ? 'bg-slate-50' : 'bg-white'}`}>
      <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className={`flex flex-col ${isReversed ? 'md:flex-row-reverse' : 'md:flex-row'} items-start gap-10 md:gap-16 h-full`}>
          {/* Content side */}
          <div className="md:w-1/2 flex flex-col justify-start">
            <h2 className="text-slate-900 text-3xl md:text-4xl lg:text-5xl font-extrabold tracking-tight">
              {headline}
            </h2>
            
            {description && (
              <p className="text-lg text-secondary mt-4 leading-relaxed">
                {description}
              </p>
            )}
            
            {/* Decorative element */}
            <div className="w-20 h-1 bg-primary my-6"></div>
            
            {/* Points */}
            <PointsSimple points={points} />
          </div>
          
          {/* Media side */}
          <div className="md:w-1/2 w-full self-stretch">
            <div className="relative rounded-2xl overflow-hidden shadow-xl ring-1 ring-black/10 transition-all duration-300 hover:shadow-2xl h-full">
              {type === 'video' ? (
                <video
                  className="block w-full h-full object-cover"
                  autoPlay
                  muted
                  loop
                  playsInline
                  preload="auto"
                  controls={false}
                  disablePictureInPicture
                  onCanPlay={(e) => e.currentTarget.play().catch(() => {})}
                  onEnded={(e) => {
                    e.currentTarget.currentTime = 0;
                    e.currentTarget.play().catch(() => {});
                  }}
                  poster={poster}
                >
                  <source src={src} type="video/mp4" />
                </video>
              ) : (
                <img
                  src={src}
                  alt={headline}
                  className="block w-full h-full object-cover"
                  loading="eager"
                  decoding="async"
                />
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export const WhyScentSection: React.FC = () => {
  const Header = () => (
    <section className="pt-8 pb-10 md:pt-12 md:pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 mb-4">Why Scent</h1>
          <div className="w-24 h-1 bg-primary mx-auto mb-6"></div>
          <p className="text-lg md:text-xl text-secondary leading-relaxed max-w-3xl mx-auto">
            Discover the science behind scent marketing and how it can transform your business.
          </p>
        </div>
      </div>
    </section>
  );

  const emotionalPoints: Point[] = [
    { icon: <Brain size={32} className="text-white" />, value: '63%',  label: 'Improvement in mood when exposed to a pleasing scent' },
    { icon: <Smile size={32} className="text-white" />, value: '75%',  label: 'Of our emotions are generated by what we smell, not what we see' },
    { icon: <Star size={32} className="text-white" />, value: '100x', label: 'People are more likely to remember what they smell vs. what they see' },
  ];

  const behaviorPoints: Point[] = [
    { icon: <TrendingUp size={32} className="text-white" />, value: '60%', label: 'Higher purchase intent' },
    { icon: <ShoppingCart size={32} className="text-white" />, value: '9%', label: 'More revenue was earned' },
    { icon: <Wallet size={32} className="text-white" />, value: '23%', label: 'More money was spent by women' },
    { icon: <ShoppingCart size={32} className="text-white" />, value: '22%', label: 'More products were purchased' },
    { icon: <Timer size={32} className="text-white" />, value: '18%', label: 'More time was spent in store' },
  ];

  return (
    <div className="bg-white text-slate-900">
      <Header />

      {/* Video section */}
      <BannerBlock
        type="video"
        src="/assets/whyscent/emotional.mp4"
        headline="Scent Makes an Emotional Impact"
        points={emotionalPoints}
      />

      {/* Image section */}
      <BannerBlock
        type="image"
        src="/assets/whyscent/behaviour.png"
        headline="Scent Drives Customer Behavior"
        points={behaviorPoints}
        isReversed={true}
        description="A study by css datatelligence compared shoppers in a scentair scented And an unscented environment. In the scented space:"
      />

      {/* CTA */}
      <section className="bg-white py-16 md:py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h3 className="text-2xl md:text-4xl font-bold text-[#0c4384]">
            Ready to craft your signature scent?
          </h3>
          <p className="text-black mt-4 text-lg max-w-2xl mx-auto">
            Elevate experience, increase conversions, and build lasting loyalty.
          </p>
          <div className="mt-8">
            <a
              href="/contact"
              className="inline-flex items-center justify-center rounded-full px-8 py-4
                         bg-primary text-white font-bold text-lg transition-colors shadow-lg hover:shadow-xl"
            >
              Get a Free Consultation
            </a>
          </div>
        </div>
      </section>
    </div>
  );
};
